### ! create index customers
PUT http://localhost:9200/customers


### ! create index products
PUT http://localhost:9200/products


### ! create index orders
PUT http://localhost:9200/orders


### ! show all indices
GET http://localhost:9200/_cat/indices?v


### ! delete index customers
DELETE http://localhost:9200/customers


### ! delete index products
DELETE http://localhost:9200/products


### ! delete index orders
DELETE http://localhost:9200/orders


### ! show all indices
GET http://localhost:9200/_cat/indices?v


### ! get customers mapping
GET http://localhost:9200/customers/_mapping


### ! update customers mapping auto detection date
PUT http://localhost:9200/customers/_mapping
Content-Type: application/json

{
    "date_detection": true,
    "dynamic_date_formats" : [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}


### ! update customers mapping auto detection numeric
PUT http://localhost:9200/customers/_mapping
Content-Type: application/json

{
    "numeric_detection": true
}


### ! get products mapping
GET http://localhost:9200/products/_mapping


### ! update products mapping auto detection date
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
    "date_detection": true,
    "dynamic_date_formats" : [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}


### ! update products mapping auto detection numeric
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
    "numeric_detection": true
}


### ! get orders mapping
GET http://localhost:9200/orders/_mapping


### ! update orders mapping auto detection date
PUT http://localhost:9200/orders/_mapping
Content-Type: application/json

{
    "date_detection": true,
    "dynamic_date_formats" : [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}


### ! update orders mapping auto detection numeric
PUT http://localhost:9200/orders/_mapping
Content-Type: application/json

{
    "numeric_detection": true
}


### ! create new customers
POST http://localhost:9200/customers/_create/ibrohim
Content-Type: application/json

{
    "name": "Ibrohim Sairony",
    "register_at" : "2023-01-01 00:00:00"
}


### ! create new customers Failed  karena menyelisihi mapping yang sudah dibuat
POST http://localhost:9200/customers/_create/joko
Content-Type: application/json

{
    "name": "Joko",
    "register_at" : "2023/01/01 00:00:00"
}


### ! get customers mapping
GET http://localhost:9200/customers/_mapping


### ! create product 1
POST http://localhost:9200/products/_create/1
Content-Type: application/json

{
    "name" : "Mie Ayam Soto",
    "price" : "3000"
}


### ! create product 2
POST http://localhost:9200/products/_create/2
Content-Type: application/json

{
    "name" : "Nasi Goreng Kuah",
    "price" : 7000
}


### ! get products mapping
GET http://localhost:9200/products/_mapping


### ! create order 1
POST http://localhost:9200/orders/_create/2
Content-Type: application/json

{
    "order_date" : "2024-08-09 12:12:12",
    "customer_id" : "ibrohim",
    "total" : [
        {
            "product_id" : "1",
            "price" : "3000",
            "quantity" : "1"
        }
    ]
}


### ! get orders mapping
GET http://localhost:9200/products/_mapping


### ! get customer doc ibrohim
GET http://localhost:9200/customers/_doc/ibrohim


### ! get customer doc notfound
GET http://localhost:9200/customers/_doc/salah


### ! get customer source ibrohim 
GET http://localhost:9200/customers/_source/ibrohim


### ! check exists ibrohim, pakai HEAD
HEAD http://localhost:9200/customers/_doc/ibrohim


### ! check exists salah, pakai HEAD
HEAD http://localhost:9200/customers/_source/salah



###  MULTI GET API ###


### ! singleIndex : get order 1 and order 2
POST http://localhost:9200/orders/_mget
Content-Type: application/json

{
    "ids" : [
        "1", "2"
    ]
}


### ! multiIndex : get order 1 and customer ibrohim
POST http://localhost:9200/_mget
Content-Type: application/json

{
    "docs" : [
        {
            "_id" : "1",
            "_index" : "orders"
        },
        {
            "_id" : "ibrohim",
            "_index" : "customers"
        },
        {
            "_id" : "salah",
            "_index" : "customers"
        }
    ]
}



###  Search API ###


### ! search all products
POST http://localhost:9200/products/_search


### ! search all products page 1
POST http://localhost:9200/products/_search?size=1&from=0


### ! search all products page 2
POST http://localhost:9200/products/_search?size=1&from=1


### ! search all products sort by pricing
POST http://localhost:9200/products/_search?sort=price:desc



###  Index API ### (dokumen sudah ada akan di replice) kalau pakai create API akan error



### ! crate product 3
POST http://localhost:9200/products/_doc/3
Content-Type: application/json

{
    "name" : "Pop Mie Rasa Baso",
    "price" : "2500"
}


### ! crate product 4
POST http://localhost:9200/products/_doc/4
Content-Type: application/json

{
    "name" : "Samsung Galaxy S40+",
    "price" : "25000000"
}


### ! crate product 5
POST http://localhost:9200/products/_doc/5
Content-Type: application/json

{
    "name" : "MacBook Air M5",
    "price" : "30000000"
}


### ! search all product
POST http://localhost:9200/products/_search



###  Update API ###



### ! update price for product 5
POST http://localhost:9200/products/_update/5
Content-Type: application/json

{
    "doc" : {
        "price" : "60000000"
    }
}



###  Delete API ###


### ! insert costumer spammer
POST http://localhost:9200/customers/_doc/spammer
Content-Type: application/json

{
    "name":"Spammer",
    "register_at" : "2024-10-10 00:00:00"
}


### ! delete customer spammer
DELETE http://localhost:9200/customers/_doc/spammer